services:
    plugin.hey:
        class: Nopolabs\Yabot\Plugins\Examples\Hey
        arguments:
            - '@message.dispatcher'
            - '@logger'
        tags:
            - { name: yabot.plugin }
