imports:
    - { resource: giphy.yml }
    - { resource: hey.yml }
    - { resource: httpserver.yml }
    - { resource: lookup.yml }
    - { resource: queue.yml }
    - { resource: reservations.yml }
    - { resource: smstext.yml }
