imports:
    - { resource: services.yml }

    - { resource: '../vendor/nopolabs/yabot/config/plugin.help.yml' }
    - { resource: '../vendor/nopolabs/yabot/config/plugin.status.yml' }
    - { resource: plugin.giphy.yml }
    - { resource: plugin.hey.yml }
    - { resource: plugin.lookup.yml }
    - { resource: plugin.nyt.yml }
    - { resource: plugin.queue.yml }
    - { resource: plugin.reservations.yml }
    - { resource: plugin.rss.yml }
    - { resource: plugin.yesOrNo.yml }
#    - { resource: plugin.smstext.yml }
