imports:
    - { resource: httpserver.yml }
    - { resource: plugin.giphy.yml }
    - { resource: plugin.hey.yml }
    - { resource: plugin.lookup.yml }
    - { resource: plugin.queue.yml }
    - { resource: plugin.reservations.yml }
    - { resource: plugin.smstext.yml }
    - { resource: queue.yml }
