services:
    plugin.rss:
        class: Nopolabs\Yabot\Plugins\Rss\RssPlugin
        arguments:
            - '@logger'
            - '@rss.service'
        tags:
            - { name: yabot.plugin }
