services:
    plugin.yesOrNo:
        class: Nopolabs\Yabot\Plugins\Examples\YesOrNoPlugin
        arguments:
            - '@guzzle'
            - '@logger'
        tags:
            - { name: yabot.plugin }
