services:
    plugin.giphy:
        class: Nopolabs\Yabot\Plugins\Giphy\GiphyPlugin
        arguments:
            - '@logger'
            - '@giphy.service'
        tags:
            - { name: yabot.plugin }

    giphy.service:
        class: Nopolabs\Yabot\Plugins\Giphy\GiphyService
        arguments:
            - '@logger'
            - '@guzzle'
