services:
    plugin.reservations:
        class: Nopolabs\Yabot\Plugins\Reservations\ReservationsPlugin
        arguments:
            - '@logger'
            - '@reservations.resources'
        tags:
            - { name: yabot.plugin }
